/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AppClientes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yeison Romero Salinas
 */
public class Vista_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Cliente
     */
    public Vista_Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_nombre = new javax.swing.JLabel();
        JTF_name = new javax.swing.JTextField();
        JB_guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_clientes = new javax.swing.JList<>();
        JB_Eliminar = new javax.swing.JButton();
        JB_limpiar = new javax.swing.JButton();
        JL_lastName = new javax.swing.JLabel();
        JTF_lastName = new javax.swing.JTextField();
        JL_email = new javax.swing.JLabel();
        JTF_email = new javax.swing.JTextField();
        JL_phone = new javax.swing.JLabel();
        JTF_phone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_nombre.setText("Nombre:");

        JTF_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_nameActionPerformed(evt);
            }
        });

        JB_guardar.setText("Guardar");
        JB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_guardarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(JL_clientes);

        JB_Eliminar.setText("Eliminar");
        JB_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EliminarActionPerformed(evt);
            }
        });

        JB_limpiar.setText("Limpiar");
        JB_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_limpiarActionPerformed(evt);
            }
        });

        JL_lastName.setText("apellido");

        JTF_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_lastNameActionPerformed(evt);
            }
        });

        JL_email.setText("email");

        JTF_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_emailActionPerformed(evt);
            }
        });

        JL_phone.setText("telefono");

        JTF_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_phoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_lastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_nombre)
                                .addGap(34, 34, 34)
                                .addComponent(JTF_name, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_phone)
                                    .addComponent(JL_email))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_email, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTF_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB_Eliminar)
                                .addGap(46, 46, 46)
                                .addComponent(JB_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JB_limpiar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_nombre)
                    .addComponent(JTF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_lastName)
                    .addComponent(JTF_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_email)
                    .addComponent(JTF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_phone)
                    .addComponent(JTF_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Eliminar)
                    .addComponent(JB_guardar)
                    .addComponent(JB_limpiar))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_nameActionPerformed
    /**
     * Es la creacion de la lista creada para los clientes 
     * y se asigna de tipo cliente
     *
     */
    private List<Cliente> lista = new ArrayList<Cliente>();

    /**
     * Esta funcion recibe el nombre del capo de texto y lo guarda en la lista
     *
     * @param evt
     */
    private void JB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_guardarActionPerformed

        
        Cliente client = new Cliente();
        client.setName(JTF_name.getText());
        client.setLastName(JTF_lastName.getText());
        client.setEmail(JTF_email.getText());
        client.setPhone(JTF_phone.getText());
        
        lista.add(client);
        actuaizarLista();
        
        JOptionPane.showMessageDialog(rootPane, "Cliente guardado"+ client.getCompleteName());
        
        limpiarCampos();
    }//GEN-LAST:event_JB_guardarActionPerformed
        private void limpiarCampos(){
        JTF_name.setText("");
        JTF_lastName.setText("");
        JTF_email.setText("");
        JTF_phone.setText("");
    }
        
    /**
     * Funcion que elimina los datos de la tabla
     *
     * @param evt
     */
    private void JB_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EliminarActionPerformed
        int indice = JL_clientes.getSelectedIndex();
        lista.remove(indice);
        actuaizarLista();
        JOptionPane.showMessageDialog(rootPane, "Se elimino correctamente");
    }//GEN-LAST:event_JB_EliminarActionPerformed

    private void JB_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_limpiarActionPerformed
        lista.clear();
        actuaizarLista();
        JOptionPane.showMessageDialog(rootPane, "se limpio la tabla");
    }//GEN-LAST:event_JB_limpiarActionPerformed

    private void JTF_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_lastNameActionPerformed

    private void JTF_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_emailActionPerformed

    private void JTF_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_phoneActionPerformed

    
    /**
     * Esta funcion actualiza los nombres que se guarden en la lista
     */
    private void actuaizarLista() {
        DefaultListModel datos = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            Cliente client = lista.get(i);
            datos.addElement(client.getCompleteName());
        }
        JL_clientes.setModel(datos);
    }
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Eliminar;
    public javax.swing.JButton JB_guardar;
    private javax.swing.JButton JB_limpiar;
    public javax.swing.JList<String> JL_clientes;
    private javax.swing.JLabel JL_email;
    private javax.swing.JLabel JL_lastName;
    private javax.swing.JLabel JL_nombre;
    private javax.swing.JLabel JL_phone;
    public javax.swing.JTextField JTF_email;
    public javax.swing.JTextField JTF_lastName;
    public javax.swing.JTextField JTF_name;
    public javax.swing.JTextField JTF_phone;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
